draft 1.2

diff --git a/auto.install b/auto.install
--- a/auto.install
+++ b/auto.install
@@ -17,13 +17,32 @@ install_packages() {
   sudo pacman -S --noconfirm \
     hyprland hyprpaper hypridle hyprlock \
     waybar kitty rofi emacs wlogout sddm \
-    python-pywal yay imagemagick base-devel \
+    python-pywal imagemagick base-devel \
     xdg-desktop-portal-hyprland \
     noto-fonts ttf-jetbrains-mono-nerd ttf-font-awesome \
     xdg-user-dirs xdg-utils || error "Package install failed"
 }
 
+install_yay() {
+  header "Installing yay AUR helper..."
+  if ! command -v yay &>/dev/null; then
+    git clone https://aur.archlinux.org/yay.git || error "Failed to clone yay"
+    cd yay || error "Failed to enter yay directory"
+    makepkg -si --noconfirm || error "Failed to build/install yay"
+    cd .. && rm -rf yay
+  else
+    echo "yay already installed. Skipping..."
+  fi
+}
+
+install_sddm_theme() {
+  header "Installing Sugar Candy SDDM Theme..."
+  yay -S --noconfirm sddm-theme-sugar-candy-git || error "Failed to install SDDM theme"
+}
+
 # Run Functions
 install_packages
+install_yay
+install_sddm_theme
 
 
